[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 10_000
via_ir = true

remappings = [
  "@contracts-bedrock/=lib/optimism/packages/contracts-bedrock/src/",
  "@contracts-bedrock-interfaces/=lib/optimism/packages/contracts-bedrock/interfaces/",
  "@solady-v0.0.245/=lib/optimism/packages/contracts-bedrock/lib/solady-v0.0.245/src/",
  "@solady/=lib/optimism/packages/contracts-bedrock/lib/solady/src/",
  "@openzeppelin/contracts=lib/optimism/packages/contracts-bedrock/lib/openzeppelin-contracts/contracts",
  "@interop-lib/=lib/interop-lib/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
